scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - host.docker.internal:9999

  - job_name: 'bot'
    scrape_interval: 5s
    static_configs:
      - targets:
          - host.docker.internal:8091

  - job_name: 'scrapper'
    scrape_interval: 5s
    static_configs:
      - targets:
          - host.docker.internal:8081
