app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true

logging:
  config: classpath:log4j2-plain.xml

client:
  base-url: ${BOT_CLIENT_BASE_URL}

database:
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
