app:
  scheduler:
    enable: true
    interval: 10
    seconds: 60
    force-check-delay: 10s

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/scrapper
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true


springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true

logging:
  config: classpath:log4j2-plain.xml

client:
  base-url: ${BOT_CLIENT_BASE_URL}

