app:
  scheduler:
    enable: true
    interval: 60
    seconds: 60
    force-check-delay: 10s
  database-access-type: jpa

retry:
  retry-type: exponential
  duration: 5
  attempts: 2
  codes: 500, 501, 502, 503, 504, 521, 522, 523, 524

bucket:
  capacity: 10
  refill:
    size: 20
    interval: 1
  cache:
    max-size: 100
    expiration-time: 10


spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/scrapper
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui
server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true

logging:
  config: classpath:log4j2-plain.xml

client:
  base-url: ${BOT_CLIENT_BASE_URL}

