app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    seconds: 40

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true

logging:
  config: classpath:log4j2-plain.xml
client:
  base-url: ${BOT_CLIENT_BASE_URL}
