app:
  telegram-token: ${TELEGRAM_API_KEY}
  retry-type: constant

client:
  base-url: ${SCRAPPER_CLIENT_BASE_URL}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
springdoc:
  swagger-ui:
    path: /swagger-ui



