app:
  telegram-token: ${TELEGRAM_API_KEY}


retry:
  retry-type: exponential
  duration: 5s
  attempts: 2
  codes: 500, 501, 502, 503, 504, 521, 522, 523, 524

client:
  base-url: ${SCRAPPER_CLIENT_BASE_URL}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
springdoc:
  swagger-ui:
    path: /swagger-ui



