CREATE TABLE chat
(
    id BIGINT PRIMARY KEY
);

CREATE TABLE link
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url         VARCHAR                  NOT NULL UNIQUE,
    last_update TIMESTAMP WITH TIME ZONE,
    last_check  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE chat_link
(
    chat_id BIGINT REFERENCES chat (id),
    link_id BIGINT REFERENCES link (id),
    PRIMARY KEY (chat_id, link_id)
);
